# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  build:
    desc: Build the project
    cmds:
      - echo "Building the project..."
      - darklua process src/main.luau out/main.lua
      - darklua minify out/main.lua out/main.min.lua
